form_fields = [
    {
        "field_type": "text",
        "field_label": "Name",
        "field_placeholder": "Enter your name",
        "is_required": True,
        "step": 1,
        "validation": {
            "min_length": 2,
            "max_length": 50,
            "pattern": "^[a-zA-Z ]+$",
        },
        "index": 0,
        "status": True,
    },
    {
        "field_type": "email",
        "field_label": "Email",
        "field_placeholder": "Enter your email",
        "is_required": True,
        "step": 1,
        "validation": {
            "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        },
        "index": 1,
        "status": True,
    },
    {
        "field_type": "phone",
        "field_label": "Phone Number",
        "field_placeholder": "Enter your phone number",
        "is_required": True,
        "step": 1,
        "validation": {
            "pattern": "^\+?[0-9]{10,15}$",
        },
        "index": 2,
        "status": True,
    },
    {
        "field_type": "textarea",
        "field_label": "Message",
        "field_placeholder": "Enter your message",
        "is_required": False,
        "step": 2,
        "validation": {
            "min_length": 10,
            "max_length": 500,
        },
        "index": 2,
        "status": True,
    },
    {
        "field_type": "date",
        "field_label": "Check-in Date",
        "field_placeholder": "Select your check-in date",
        "is_required": True,
        "step": 3,
        "validation": {
            "pattern": "^\d{4}-\d{2}-\d{2}$",
        },
        "index": 0,
        "status": True,
    },
    {
        "field_type": "number",
        "field_label": "Number of Guests",
        "field_placeholder": "Enter number of guests",
        "is_required": True,
        "step": 3,
        "validation": {
            "min_value": 1,
            "max_value": 10,
        },
        "index": 2,
        "status": True,
    },
    {
        "field_type": "file",
        "field_label": "Upload ID Proof",
        "field_placeholder": "Upload your ID document",
        "is_required": False,
        "step": 9,
        "index": 0,
        "status": True,
    },
    {
        "field_type": "time",
        "field_label": "Estimated Arrival Time",
        "field_placeholder": "Select arrival time",
        "is_required": False,
        "step": 9,
        "validation": {"pattern": "^([01]?[0-9]|2[0-3]):[0-5][0-9]$"},
        "index": 1,
        "status": True,
    },
    {
        "field_type": "color",
        "field_label": "Favorite Room Color",
        "field_placeholder": "Pick a color",
        "is_required": False,
        "step": 9,
        "index": 2,
        "status": True,
    },
    {
        "field_type": "url",
        "field_label": "Personal Website or Portfolio",
        "field_placeholder": "Enter URL",
        "is_required": False,
        "step": 9,
        "validation": {"pattern": "^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$"},
        "index": 3,
        "status": True,
    },
    {
        "field_type": "range",
        "field_label": "Budget Range (USD)",
        "field_placeholder": "Set your budget",
        "is_required": False,
        "step": 9,
        "validation": {
            "min_value": 50,
            "max_value": 1000,
        },
        "index": 4,
        "status": True,
    },
    {
        "field_type": "hidden",
        "field_label": "Referral Code",
        "is_required": False,
        "step": 9,
        "index": 5,
        "status": True,
    },
    {
        "field_type": "password",
        "field_label": "Secure Access Code",
        "field_placeholder": "Enter access code",
        "is_required": False,
        "step": 9,
        "validation": {
            "min_length": 6,
        },
        "index": 6,
        "status": True,
    },
    {
        "field_type": "image",
        "field_label": "Profile Picture",
        "field_placeholder": "Upload your photo",
        "is_required": False,
        "step": 9,
        "index": 7,
        "status": True,
    },
    {
        "field_type": "signature",
        "field_label": "Digital Signature",
        "field_placeholder": "Sign here",
        "is_required": False,
        "step": 9,
        "index": 8,
        "status": True,
    },
    {
        "field_type": "toggle",
        "field_label": "Need Airport Pickup?",
        "is_required": False,
        "step": 9,
        "index": 9,
        "status": True,
    },
]


default_form_fields = [
    {
        "field_type": "text",
        "field_label": "Name",
        "field_placeholder": "Enter your name",
        "is_required": True,
        "step": 1,
        "validation": {
            "min_length": 2,
            "max_length": 50,
            "pattern": "^[a-zA-Z ]+$",
        },
        "index": 0,
        "status": True,
    },
    {
        "field_type": "email",
        "field_label": "Email",
        "field_placeholder": "Enter your email",
        "is_required": True,
        "step": 1,
        "validation": {
            "pattern": "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        },
        "index": 1,
        "status": True,
    },
    {
        "field_type": "phone",
        "field_label": "Phone Number",
        "field_placeholder": "Enter your phone number",
        "is_required": True,
        "step": 1,
        "validation": {
            "pattern": "^\+?[0-9]{10,15}$",
        },
        "index": 2,
        "status": True,
    },
    {
        "field_type": "textarea",
        "field_label": "Message",
        "field_placeholder": "Enter your message",
        "is_required": False,
        "step": 2,
        "validation": {
            "min_length": 10,
            "max_length": 500,
        },
        "index": 2,
        "status": True,
    },
]
